- name: Download dropbox v{{ dropbox_version }} setup script
  get_url:
    url: https://www.dropbox.com/download?dl=packages/{{ ansible_distribution | lower }}/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    dest: /tmp/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    mode: 755
  tags: dropbox-download
  register: dropbox_setup_scriptfile

- name: install dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb file
  apt:
    deb: "{{ dropbox_setup_scriptfile.dest }}"
  when: dropbox_setup_scriptfile.changed
  tags: dropbox-install-deb